ProvaCandidato.Web/Controllers/CidadesController.cs
using ProvaCandidato.Controllers.Common;
using ProvaCandidato.Data.Entidade;

namespace ProvaCandidato.Controllers
{
	public class CidadesController : BasicCRUDController<Cidade>
	{

	}
}

ProvaCandidato.Web/Controllers/ClientesController.cs
using ProvaCandidato.Controllers.Common;
using ProvaCandidato.Data.Entidade;

namespace ProvaCandidato.Controllers
{
	public class ClientesController : BasicCRUDController<Cliente>
	{

	}
}

ProvaCandidato.Web/Controllers/Common/BasicCRUDController.cs
using ProvaCandidato.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ProvaCandidato.Controllers.Common
{
	public abstract class BasicCRUDController<TEntidade> : Controller where TEntidade : class
	{
		protected ContextoPrincipal db = new ContextoPrincipal();

		public ActionResult Index() => View(db.Set<TEntidade>().ToList());

		[HttpGet]
		public ActionResult Details(int? id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var entidade = db.Set<TEntidade>().Find(id); // Make async.

			return entidade == null ?
				HttpNotFound() :
				(ActionResult) View(entidade);
		}

		[HttpGet]
		public ActionResult Create() => View();

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(TEntidade entidade)
		{
			if (ModelState.IsValid)
			{
				db.Set<TEntidade>().Add(entidade);
				db.SaveChanges(); // Make async.
				return RedirectToAction("Index");
			}

			return View(entidade);
		}

		public ActionResult Edit(int? id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var entidade = db.Set<TEntidade>().Find(id);

			return entidade == null ?
				HttpNotFound() :
				(ActionResult) View(entidade);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(TEntidade entidade)
		{
			if (ModelState.IsValid)
			{
				db.Entry(entidade).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(entidade);
		}

		public ActionResult Delete(int? id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var entidade = db.Set<TEntidade>().Find(id); // Make async.

			return entidade == null ?
				HttpNotFound() :
				(ActionResult) View(entidade);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			var entidade = db.Set<TEntidade>().Find(id);
			db.Set<TEntidade>().Remove(entidade);
			db.SaveChanges(); // Make async.
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
				db.Dispose();

			base.Dispose(disposing);
		}

		protected override void OnException(ExceptionContext filterContext)
		{
			if (filterContext != null)
			{
				filterContext.ExceptionHandled = true;
				AddException($"{filterContext.Exception.Message}");
			}
			base.OnException(filterContext);
		}

		// Pode ser usado com JavaScript pra mostrar um toast na tela
		public void AddException(string message) =>
			TempData["ERROR"] = message;
	}
}

ProvaCandidato.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ProvaCandidato.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.NomeEmpresa = System.Configuration.ConfigurationManager.AppSettings["nomeempresa"];
			return View();
		}
	}
}

ProvaCandidato.Web/Views/Cidades/Create.cshtml
@model ProvaCandidato.Data.Entidade.Cidade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cidade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaCandidato.Web/Views/Cidades/Delete.cshtml
@model ProvaCandidato.Data.Entidade.Cidade

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProvaCandidato.Web/Views/Cidades/Details.cshtml
@model ProvaCandidato.Data.Entidade.Cidade

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Codigo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProvaCandidato.Web/Views/Cidades/Edit.cshtml
@model ProvaCandidato.Data.Entidade.Cidade

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cidade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Codigo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaCandidato.Web/Views/Cidades/Index.cshtml
@model IEnumerable<ProvaCandidato.Data.Entidade.Cidade>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Codigo }) |
            @Html.ActionLink("Details", "Details", new { id=item.Codigo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Codigo })
        </td>
    </tr>
}

</table>

ProvaCandidato.Web/Views/Clientes/Create.cshtml
@model ProvaCandidato.Data.Entidade.Cliente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaCandidato.Web/Views/Clientes/Delete.cshtml
@model ProvaCandidato.Data.Entidade.Cliente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidade.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProvaCandidato.Web/Views/Clientes/Details.cshtml
@model ProvaCandidato.Data.Entidade.Cliente

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cidade.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Codigo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProvaCandidato.Web/Views/Clientes/Edit.cshtml
@model ProvaCandidato.Data.Entidade.Cliente

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Codigo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CidadeId, "CidadeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CidadeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaCandidato.Web/Views/Clientes/Index.cshtml
@model IEnumerable<ProvaCandidato.Data.Entidade.Cliente>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cidade.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ativo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Codigo }) |
            @Html.ActionLink("Details", "Details", new { id=item.Codigo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Codigo })
        </td>
    </tr>
}

</table>

ProvaCandidato.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Prova Candidado(a) ASP.NET MVC</title>
    @Styles.Render("~/Assets/StyleSheets/bootstrap.min.css")
    @Scripts.Render("~/Assets/Scripts/modernizr-*")
    @RenderSection("head", required: false)
</head>
<body>
    <div class="container body-content">
        <h1 class="title">@ViewBag.NomeEmpresa</h1>
        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Instruções", "Index", "Home")</li>
                        <li>@Html.ActionLink("Cliente", "Index", "Clientes")</li>
                        <li>@Html.ActionLink("Cidade", "Index", "Cidades")</li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="conteudo">
            @if (@TempData["UserMessage"] != null)
            {
                <div id="alert-success" class="alert alert-success">
                    <strong>Sucesso</strong> @TempData["UserMessage"]
                </div>
                TempData["UserMessage"] = null;
            }
            @RenderBody()
        </div>
        <footer>
            <div class="linha">2017 &copy; - Parametrize o Nome da Empresa Aqui</div>
        </footer>
    </div>
    @Scripts.Render("~/Assets/Scripts/jquery-ui-1.10.2.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>